providers:
  docker:
    exposedByDefault: false
    network: proxy
    watch: true
entrypoints:
  http:
    address: ":80"
    forwardedHeaders:
      insecure: true
      trustedIPs:
        - "127.0.0.1/32"
        - "172.0.0.1/8"
        - "192.168.0.0/16"
api:
  dashboard: true
  insecure: false
log:
  level: INFO
experimental:
  http3: true
global:
  sendAnonymousUsage: false
accessLog:
  filePath: "/var/logs/access.log"
  bufferingsize: 100
  filters:
    statuscodes: 
      - "100-599"
    retryattempts: true
    minduration: "100ms"
  fields:
    names:
      StartUTC: drop